[
{ "tag": "struct", "ns": 0, "name": "Big", "id": 0, "location": "/home/martin/stage/cl-cffi-callback-test/include/wal.h:1:8", "bit-size": 128, "bit-alignment": 64, "fields": [{ "tag": "field", "name": "i0", "bit-offset": 0, "bit-size": 64, "bit-alignment": 64, "type": { "tag": ":unsigned-long", "bit-size": 64, "bit-alignment": 64 } }, { "tag": "field", "name": "i1", "bit-offset": 64, "bit-size": 64, "bit-alignment": 64, "type": { "tag": ":unsigned-long", "bit-size": 64, "bit-alignment": 64 } }] },
{ "tag": "typedef", "ns": 0, "name": "Big", "location": "/home/martin/stage/cl-cffi-callback-test/include/wal.h:7:20", "type": { "tag": ":struct", "name": "Big", "id": 1 } },
{ "tag": "enum", "ns": 0, "name": "CallbackResult", "id": 0, "location": "/home/martin/stage/cl-cffi-callback-test/include/wal.h:8:6", "fields": [{ "tag": "field", "name": "RESULT_OK", "value": 0 }, { "tag": "field", "name": "RESULT_FAIL", "value": 2147483648 }] },
{ "tag": "typedef", "ns": 0, "name": "CallbackResult", "location": "/home/martin/stage/cl-cffi-callback-test/include/wal.h:10:29", "type": { "tag": ":enum", "name": "CallbackResult", "id": 0 } },
{ "tag": "typedef", "ns": 0, "name": "Callback0", "location": "/home/martin/stage/cl-cffi-callback-test/include/wal.h:11:26", "type": { "tag": ":function-pointer" } },
{ "tag": "typedef", "ns": 0, "name": "Callback1", "location": "/home/martin/stage/cl-cffi-callback-test/include/wal.h:12:26", "type": { "tag": ":function-pointer" } },
{ "tag": "function", "name": "make_big", "ns": 0, "location": "/home/martin/stage/cl-cffi-callback-test/include/wal.h:13:5", "variadic": false, "inline": false, "storage-class": "none", "parameters": [{ "tag": "parameter", "name": "a", "type": { "tag": ":unsigned-long", "bit-size": 64, "bit-alignment": 64 } }, { "tag": "parameter", "name": "b", "type": { "tag": ":unsigned-long", "bit-size": 64, "bit-alignment": 64 } }], "return-type": { "tag": "Big" } },
{ "tag": "function", "name": "run0", "ns": 0, "location": "/home/martin/stage/cl-cffi-callback-test/include/wal.h:14:6", "variadic": false, "inline": false, "storage-class": "none", "parameters": [{ "tag": "parameter", "name": "cb", "type": { "tag": "Callback0" } }, { "tag": "parameter", "name": "big", "type": { "tag": "Big" } }], "return-type": { "tag": ":void" } },
{ "tag": "function", "name": "run1", "ns": 0, "location": "/home/martin/stage/cl-cffi-callback-test/include/wal.h:15:6", "variadic": false, "inline": false, "storage-class": "none", "parameters": [{ "tag": "parameter", "name": "cb", "type": { "tag": "Callback1" } }, { "tag": "parameter", "name": "big", "type": { "tag": ":pointer", "type": { "tag": "Big" } } }], "return-type": { "tag": ":void" } }
]
